services:
  i2pd:
    image: purplei2p/i2pd:latest
    container_name: mft-i2pd
    ports:
      - "4444:4444" # HTTP Proxy
      - "4447:4447" # Socks Proxy
      - "7656:7656" # SAM Bridge
      - "7070:7070" # Web Console
    volumes:
      - i2pd-data:/var/lib/i2pd
    command: --sam.enabled=true --sam.address=0.0.0.0 --sam.port=7656 --http.address=0.0.0.0 --http.port=7070 --http.strictheaders=false --log=stdout --loglevel=info
    networks:
      - i2p-net

volumes:
  i2pd-data:


networks:
  i2p-net:
